// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW830MCh3XcxkCM7qVSi1xukbZHqb9ZA4',
    appId: '1:949364282512:web:01cd71e69241740d1d3415',
    messagingSenderId: '949364282512',
    projectId: 'music-team-roster',
    authDomain: 'music-team-roster.firebaseapp.com',
    storageBucket: 'music-team-roster.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3uQM272MdCQLTP5LXxhnzRKCo04_kZQ',
    appId: '1:949364282512:android:657e6255e56f56d21d3415',
    messagingSenderId: '949364282512',
    projectId: 'music-team-roster',
    storageBucket: 'music-team-roster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_53Tda9joYYT3JrvCm3GbUldWZYb_HM',
    appId: '1:949364282512:ios:056c92bd00c69bc51d3415',
    messagingSenderId: '949364282512',
    projectId: 'music-team-roster',
    storageBucket: 'music-team-roster.appspot.com',
    iosClientId: '949364282512-5c3b749gsnn43232dgqapd30m4222ec8.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicRoster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_53Tda9joYYT3JrvCm3GbUldWZYb_HM',
    appId: '1:949364282512:ios:056c92bd00c69bc51d3415',
    messagingSenderId: '949364282512',
    projectId: 'music-team-roster',
    storageBucket: 'music-team-roster.appspot.com',
    iosClientId: '949364282512-5c3b749gsnn43232dgqapd30m4222ec8.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicRoster',
  );
}
